language: python
python:
    - "2.7"
    - "3.4"

sudo: required

install:
    - "sudo pip install -r requirements.txt"
    - "sudo pip install coverage"
script:
    - "coverage run --source=schemagic setup.py test"